---
apiVersion: v1
kind: Service
metadata:
  name: crew-app-service
  namespace: default
spec:
  selector:
    app: crew-app
  ports:
    - name: crew-app-port
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}
      nodePort: {{ .Values.app.service.nodePort }}
  type: {{ .Values.app.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: default
spec:
  selector:
    app: mysql
  ports:
    - name: mysql-port
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}
  type: {{ .Values.mysql.service.type }}